SET HEADING OFF
SET VERIFY OFF
SET FEEDBACK OFF

WHENEVER SQLERROR EXIT SQL.SQLCODE

CREATE USER JERX_G2Hello_DBA IDENTIFIED BY 12345678
  DEFAULT TABLESPACE DSDATA
  TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DSDATA
QUOTA UNLIMITED ON DSINDX
QUOTA UNLIMITED ON RTDATA
QUOTA UNLIMITED ON RTINDX
QUOTA UNLIMITED ON RTBLOB
QUOTA UNLIMITED ON WKDATA
QUOTA UNLIMITED ON WKINDX
QUOTA UNLIMITED ON WKBLOB
;

GRANT CREATE PROCEDURE TO JERX_G2Hello_DBA;
GRANT CREATE PUBLIC SYNONYM TO JERX_G2Hello_DBA;
GRANT CREATE SEQUENCE TO JERX_G2Hello_DBA;
GRANT CREATE SESSION TO JERX_G2Hello_DBA;
GRANT CREATE SYNONYM TO JERX_G2Hello_DBA;
GRANT CREATE TABLE TO JERX_G2Hello_DBA;
GRANT CREATE TRIGGER TO JERX_G2Hello_DBA;
GRANT CREATE TYPE TO JERX_G2Hello_DBA;
GRANT CREATE VIEW TO JERX_G2Hello_DBA;

GRANT DBA TO JERX_G2Hello_DBA;
GRANT IMP_FULL_DATABASE TO JERX_G2Hello_DBA;
GRANT EXP_FULL_DATABASE TO JERX_G2Hello_DBA;

exit;