create tablespace WKDATA DSDATA DATAFILE 'DSDATA.dat' SIZE 40M AUTOEXTEND ON ONLINE;
create tablespace WKDATA DSINDX DATAFILE 'DSINDX.dat' SIZE 40M AUTOEXTEND ON ONLINE;
create tablespace WKDATA RTDATA DATAFILE 'RTDATA.dat' SIZE 40M AUTOEXTEND ON ONLINE;
create tablespace WKDATA RTINDX DATAFILE 'RTINDX.dat' SIZE 40M AUTOEXTEND ON ONLINE;
create tablespace WKDATA RTBLOB DATAFILE 'RTBLOB.dat' SIZE 40M AUTOEXTEND ON ONLINE;
create tablespace WKDATA WKDATA DATAFILE 'WKDATA.dat' SIZE 40M AUTOEXTEND ON ONLINE;
create tablespace WKDATA WKINDX DATAFILE 'WKINDX.dat' SIZE 40M AUTOEXTEND ON ONLINE;
create tablespace WKDATA WKBLOB DATAFILE 'WKBLOB.dat' SIZE 40M AUTOEXTEND ON ONLINE;
